version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  database:
    container_name: db
    image: mysql:8.0.15
    volumes:
      - /var/lib/mysql
      - ./src/main/resources/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: 'Tax'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '12345678'
